PIC18F Project Template: Main Program
Main Program
This module contains the main function.
Files
file main.c
Main Program.
Functions
void main (void)
Detailed Description
This module contains the main function.
Function Documentation
void main (void)
Definition at line 54 of file main.c.
References ampel(), ENABLED, hw_init(), LED(), LEDGREEN, LEDRED, LEDYELLOW, OFF, ON, and TOGGLE.
 {
     // PIC initialisieren
     hw_init ();
     // Millisekundenticker
     uint32_t u32msTicker = 0;
 #ifdef EGGTIMER
     EggTimerInit ();
 #endif
 #ifdef BLINK
     LED (LEDGREEN, ENABLED);
     LED (LEDYELLOW, ENABLED);
     LED (LEDRED, ENABLED);
     LED (LEDGREEN, ON);
     LED (LEDYELLOW, OFF);
     LED (LEDRED, ON);
 #endif
     while (TRUE)
     {
 #ifdef EGGTIMER
         u8UpdateMsTicker (& u32msTicker);
         EggTimer (& u32msTicker);
 #endif
 #ifdef BLINK
         LED (LEDGREEN, TOGGLE);
         LED (LEDYELLOW, TOGGLE);
         LED (LEDRED, TOGGLE);
 #endif
 #ifdef AMPEL
         ampel ();
 #endif
     }
 }